services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=sistemamoeda
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'

    volumes:
      - ./data:/var/opt/postgres/data
      - ./log:/var/opt/postgres/log
  app:
    build: src
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sistemamoeda
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_CONFIG_IMPORT=optional:file:.env[.properties]
      - SPRING_CONFIG_ADDITIONAL_LOCATION=optional:file:.env

    volumes:
      - ./data:/var/opt/postgres/data